### ISSUE TITLE
検索後ページ-mana

### ISSUE THREAD

**Issue by Yuya-Ito325** [Yuya-Ito325/DateShare#7]
- [x] プラン一覧表示
- スクロールしてセルがある分だけ表示する

- [x] セル内
- 写真
- タイトル
- 説明文
- タグ(最大3つ)
- ユーザーネーム
- お気に入りボタン

**Comment by HappyMana** [comment]
1/15までにできなかったら、片方の食費肩代わりします。

**Comment by HappyMana** [comment]
理想画面
![スクリーンショット 2022-01-26 14 10 46](https://user-images.githubusercontent.com/73377985/151107407-1ede28b7-825b-47d3-9484-67d5f8b085b2.png)
